paul_maxwell_students_accounting_homepage:
    pattern:  /
    defaults: { _controller: PaulMaxwellStudentsAccountingBundle:Default:index }

paul_maxwell_students_accounting_specialities:
    pattern: /specialities
    defaults: { _controller: PaulMaxwellStudentsAccountingBundle:Default:specialitiesList }

paul_maxwell_students_accounting_groups:
    pattern: /groups
    defaults: { _controller: PaulMaxwellStudentsAccountingBundle:Default:groupsList }

paul_maxwell_students_accounting_students:
    pattern: /students
    defaults: { _controller: PaulMaxwellStudentsAccountingBundle:Default:studentsList }

paul_maxwell_students_accounting_students_by_group:
    pattern: /students/bygroup/{id_group}
    defaults: { _controller: PaulMaxwellStudentsAccountingBundle:Default:studentsList }
    requirements: { id_group: "[0-9]+" }
